apiVersion: v1
kind: ConfigMap
metadata:
  name: jwt-public-key
data:
  public_key.pem: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx+swGigw0SdAG/xF1Qqo
    5ckTaY7vyd7oq7IveSuBGinl2UDfw7NfDvdBBkv6PbAOGQfmB6/g/NZS2s7Mg8FT
    uhsLVNugaxQpimtBIzxcNgysmQC2BNBFSCwy1GHutsNEHphwot7NNX5FOxAdfpYl
    B4b4vK+tEvzIMtQKPX5H8HFxxYkwjpoKToQSNirZQsRjvKbRp4a8jXBO2/cwcCot
    DFHBdSnVJMSeVzeFVmdxNeGR1mjg86Lg6Vdpn5I5xM7bEn3Ckw7Z2elFXU5Smn8e
    kCG0PCxWvgAD6vO3O7csKvz+iGW5vL9y+BvpNSvuIBs2ZRoP5/8q/TUZNDl4WNmY
    XQIDAQAB
    -----END PUBLIC KEY-----
